# Generated by Django 3.0 on 2024-04-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRSApp', '0027_auto_20240429_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rform',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RRSApp.Train'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='profile.png', upload_to='Profiles/'),
        ),
    ]
